name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '8.x'
    - name: Install dependencies
      run: |
        npm install
        npm install -D @babel/cli @babel/core @babel/node
    - name: Test
      run: |
        npm test
    - name: Build
      run: |
        npm run build
